/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief IOCONCLKDIV0 */
#define IOCON_PIO_CLKDIV0 0x00u
/*!
 * @brief Enable hysteresis */
#define IOCON_PIO_HYS_EN 0x20u
/*!
 * @brief Input not invert */
#define IOCON_PIO_INV_DI 0x00u
/*!
 * @brief Selects pull-up function */
#define IOCON_PIO_MODE_PULLUP 0x10u
/*!
 * @brief Disables Open-drain function */
#define IOCON_PIO_OD_DI 0x00u
/*!
 * @brief Bypass input filter */
#define IOCON_PIO_SMODE_BYPASS 0x00u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_0_MODE_INACTIVE 0x00u
/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_0_OD_ENABLED 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO0_1_MODE_INACTIVE 0x00u
/*!
 * @brief Open-drain mode.: Open-drain mode enabled. Remark: This is not a true open-drain mode. */
#define PIO0_1_OD_ENABLED 0x01u
/*!
 * @brief
 * Selects function mode (on-chip pull-up/pull-down resistor control).
 * : Inactive.
 * Inactive (no pull-down/pull-up resistor enabled).
 */
#define PIO1_2_MODE_INACTIVE 0x00u

/*! @name PIO0_24 (number 20), CN1[10]/PIO0_24
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 24U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PIO0_25 (number 19), CN1[11]/PIO0_25
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 25U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN_MASK (1U << 25U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PIO0_4 (number 6), K3/CN1[35]/PIO0_4/ADC_11/TRSTN/WAKEUP
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K3_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_K3_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_K3_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_K3_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_K3_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name PIO0_12 (number 4), K1/CN1[25]/PIO0_12
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_K1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_K1_GPIO_PIN_MASK (1U << 12U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_K1_PORT 0U                   /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_K1_PIN 12U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_K1_PIN_MASK (1U << 12U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_0 (number 36), CN1[39]/PIO0_0/ACMP_I1/TDO
  @{ */
#define BOARD_INITPINS_SCL_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_SCL_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SCL_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO0_1 (number 24), CN1[38]/PIO0_1/ACMP_I2/CLKIN/TDI
  @{ */
#define BOARD_INITPINS_SDA_PORT 0U                  /*!<@brief PORT device index: 0 */
#define BOARD_INITPINS_SDA_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDA_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name PIO1_2 (number 16), LD1[2]/CN1[29]/PIO1_2/CAPT_X3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_RED_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_RED_PORT 1U                  /*!<@brief PORT device index: 1 */
#define BOARD_INITPINS_LED_RED_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M0P */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
